#!/usr/bin/env bash

# start on 180114, real the final ones

# =======================
# TODO(FINAL2): again, only the basic baselines ...
# {zmt}/baselines
# x45
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../en_de_data_z5/ -t znmt --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0002" -z 8 -p 0
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0002 dicts_rthres 30000" -z 8 -p 3

# x47 on en_de
# continue
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../en_de_data_z5/ -t znmt --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217x45_base/{src,trg}.v reload_model_name ../z1217x45_base/zbest.model reload ZZ no_reload_training_progress ZZ  no_rebuild_dicts ZZ valid_freq 2500 validate0 ZZ" -z 6 -p 0
# raml
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../en_de_data_z5/ -t znmt --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217x45_base/{src,trg}.v reload_model_name ../z1217x45_base/zbest.model reload ZZ no_reload_training_progress ZZ  no_rebuild_dicts ZZ valid_freq 2500 raml_samples 1 validate0 ZZ" -z 6 -p 1
# err
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../en_de_data_z5/ -t znmt --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217x45_base/{src,trg}.v reload_model_name ../z1217x45_base/zbest.model reload ZZ no_reload_training_progress ZZ  no_rebuild_dicts ZZ valid_freq 2500 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 0 t2_err_gold_mode gold" -z 6 -p 2
# err
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../en_de_data_z5/ -t znmt --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217x45_base/{src,trg}.v reload_model_name ../z1217x45_base/zbest.model reload ZZ no_reload_training_progress ZZ  no_rebuild_dicts ZZ valid_freq 2500 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 1 t2_err_gold_mode gold" -z 6 -p 3
# err
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../en_de_data_z5/ -t znmt --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217x45_base/{src,trg}.v reload_model_name ../z1217x45_base/zbest.model reload ZZ no_reload_training_progress ZZ  no_rebuild_dicts ZZ valid_freq 2500 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 2 t2_err_gold_mode gold" -z 6 -p 5
# err
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../en_de_data_z5/ -t znmt --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217x45_base/{src,trg}.v reload_model_name ../z1217x45_base/zbest.model reload ZZ no_reload_training_progress ZZ  no_rebuild_dicts ZZ valid_freq 2500 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_lambda 1.0 t2_bad_maxlen 2 t2_err_gold_mode gold" -z 6 -p 7

# x48 on zh_en
# continue
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 2500 validate0 ZZ" -z 6 -p 0
# raml
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 2500 raml_samples 1 validate0 ZZ" -z 6 -p 3
# --> RR: but they all drop about 0.5 ...
# err
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 2500 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 0 t2_err_gold_mode gold" -z 6 -p 5
# err
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 2500 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 1 t2_err_gold_mode gold" -z 6 -p 6
# err
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 2500 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 2 t2_err_gold_mode gold" -z 6 -p 7

# ============================
# x48: err with med
# -------- this group drops -1/-2
# no dropouts
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.0 idrop_embedding 0.0 drop_hidden 0.0 drop_embedding 0.0 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 2 t2_err_gold_mode gold" -z 6 -p 3
# rebased
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 2 t2_err_gold_mode based" -z 6 -p 5
# no-matched
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 2 t2_err_gold_mode gold t2_err_match_nope" -z 6 -p 6
# no-matched rebased
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 2 t2_err_gold_mode based t2_err_match_nope" -z 6 -p 7

# x47: err with merge
# no dropouts (36/37)
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.0 idrop_embedding 0.0 drop_hidden 0.0 drop_embedding 0.0 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_nga ZZ t2_nga_n 4 t2_nga_range 4 t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 2 t2_err_gold_mode gold" -z 6 -p 0
# with dropouts (38 around)
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_nga ZZ t2_nga_n 4 t2_nga_range 4 t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 2 t2_err_gold_mode gold" -z 6 -p 1
# ***** rebased (+0.2)
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_nga ZZ t2_nga_n 4 t2_nga_range 4 t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 2 t2_err_gold_mode based" -z 6 -p 2
# no-matched (37 around)
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_nga ZZ t2_nga_n 4 t2_nga_range 4 t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 2 t2_err_gold_mode gold t2_err_match_nope" -z 6 -p 5
# no-matched rebased (37 around)
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_nga ZZ t2_nga_n 4 t2_nga_range 4 t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 2 t2_err_gold_mode based t2_err_match_nope" -z 6 -p 7

# ======================
# 0116: start again from zr1, beam with no drops
# x48
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zr1.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 2 t2_err_gold_mode gold t2_beam_nodrop ZZ" -z 6 -p 3
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zr1.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 2 t2_err_gold_mode based t2_beam_nodrop ZZ" -z 6 -p 5
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zr1.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 1 t2_err_gold_mode gold t2_beam_nodrop ZZ" -z 6 -p 6
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zr1.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 1 t2_err_gold_mode based t2_beam_nodrop ZZ" -z 6 -p 7
# x47
# TODO: NOT YET GET GPU TO RUN
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zr1.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_nga ZZ t2_nga_n 4 t2_nga_range 4 t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 2 t2_err_gold_mode gold t2_beam_nodrop ZZ" -z 6 -p 0
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zr1.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_nga ZZ t2_nga_n 4 t2_nga_range 4 t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 2 t2_err_gold_mode based t2_beam_nodrop ZZ" -z 6 -p 1
# x44
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zr1.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_nga ZZ t2_nga_n 4 t2_nga_range 4 t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 1 t2_err_gold_mode based t2_beam_nodrop ZZ" -z 6 -p 1


# ===========================
# 0118: start from another one of baselines/ze1: 34.89
# ** also it will be fine to focus on med, because with larger t2_err_seg_minlen, it can be similar to nga
# x48
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../../baselines/ze/{src,trg}.v reload_model_name ../../baselines/ze/zp1.m reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 2 t2_err_gold_mode gold t2_err_seg_minlen 1 t2_err_mcov_thresh 0.25" -z 6 -p 3
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../../baselines/ze/{src,trg}.v reload_model_name ../../baselines/ze/zp1.m reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 2 t2_err_gold_mode gold t2_err_seg_minlen 2 t2_err_mcov_thresh 0.25" -z 6 -p 5
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../../baselines/ze/{src,trg}.v reload_model_name ../../baselines/ze/zp1.m reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 2 t2_err_gold_mode gold t2_err_seg_minlen 3 t2_err_mcov_thresh 0.25" -z 6 -p 6
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../../baselines/ze/{src,trg}.v reload_model_name ../../baselines/ze/zp1.m reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 2 t2_err_gold_mode gold t2_err_seg_minlen 4 t2_err_mcov_thresh 0.25" -z 6 -p 7
# x47
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../../baselines/ze/{src,trg}.v reload_model_name ../../baselines/ze/zp1.m reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 2 t2_err_gold_mode based t2_err_seg_minlen 2 t2_err_mcov_thresh 0.25" -z 6 -p 0
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../../baselines/ze/{src,trg}.v reload_model_name ../../baselines/ze/zp1.m reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 2 t2_err_gold_mode based t2_err_seg_minlen 3 t2_err_mcov_thresh 0.25" -z 6 -p 1
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../../baselines/ze/{src,trg}.v reload_model_name ../../baselines/ze/zp1.m reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 2 t2_err_gold_mode based t2_err_seg_minlen 4 t2_err_mcov_thresh 0.25" -z 6 -p 2
# x44
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../../baselines/ze/{src,trg}.v reload_model_name ../../baselines/ze/zp2.m reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_lambda 0.1 t2_bad_maxlen 0 t2_err_gold_mode based t2_err_seg_minlen 3 t2_err_mcov_thresh 0.25" -z 6 -p 0

# =============================
# 01.19, ok, still using a better init point and smaller lrate, run for longer time
# x48
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zr1.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_maxlen 0 t2_err_gold_mode gold t2_err_seg_minlen 1" -z 6 -p 4
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zr1.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_maxlen 0 t2_err_gold_mode gold t2_err_seg_minlen 2" -z 6 -p 5
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zr1.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_maxlen 0 t2_err_gold_mode gold t2_err_seg_minlen 4" -z 6 -p 6
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zr1.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_maxlen 0 t2_err_gold_mode gold t2_err_seg_minlen 4 t2_err_match_addfirst" -z 6 -p 7
# x47
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zr1.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_maxlen 0 t2_err_gold_mode based t2_err_seg_minlen 1" -z 6 -p 0
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zr1.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_maxlen 0 t2_err_gold_mode based t2_err_seg_minlen 2" -z 6 -p 1
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zr1.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_maxlen 0 t2_err_gold_mode based t2_err_seg_minlen 4" -z 6 -p 2
# x44
# -- seems not good for add-first
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../z1217_base/{src,trg}.v reload_model_name ../z1217_base/zr1.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_maxlen 0 t2_err_gold_mode based t2_err_seg_minlen 4 t2_err_match_addfirst" -z 6 -p 0


# ================================
# 01.22: still not good for based versions
# x44: run from start
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 dicts_rthres 30000 train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_maxlen 0 t2_err_gold_mode based t2_err_seg_minlen 4 no_validate_freq ZZ validate_epoch ZZ" -z 6 -p 0
# -> based on 0.0001's best point: 36.93
# x48
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../../baselines/ze1/{src,trg}.v reload_model_name ../../baselines/ze1/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_maxlen 0 t2_err_gold_mode based t2_err_seg_minlen 3 t2_err_seg_freq_token 100 t2_err_seg_extend_range 5" -z 6 -p 4
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../../baselines/ze1/{src,trg}.v reload_model_name ../../baselines/ze1/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_maxlen 0 t2_err_gold_mode based t2_err_seg_minlen 3 t2_err_seg_freq_token 100" -z 6 -p 5
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../../baselines/ze1/{src,trg}.v reload_model_name ../../baselines/ze1/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_maxlen 0 t2_err_gold_mode based t2_err_seg_minlen 4 t2_err_seg_freq_token 100" -z 6 -p 6
# x47
# common
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../../baselines/ze1/{src,trg}.v reload_model_name ../../baselines/ze1/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_maxlen 0 t2_err_gold_mode based t2_err_seg_minlen 4" -z 6 -p 0
# small lrate
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.00005 dicts ../../baselines/ze1/{src,trg}.v reload_model_name ../../baselines/ze1/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_maxlen 0 t2_err_gold_mode based t2_err_seg_minlen 4" -z 6 -p 1
# no rec-drop
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.0 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.0001 dicts ../../baselines/ze1/{src,trg}.v reload_model_name ../../baselines/ze1/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_maxlen 0 t2_err_gold_mode based t2_err_seg_minlen 4" -z 6 -p 2

# ------------------------
# 18.01.25: maybe using thresholds is reasonable!
# -- and try using the "epoch-valid-0.0001" baseline of baselines/ze_ev/zbest.model
# x45: run from start
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 dicts_rthres 30000 train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_maxlen 0 t2_err_gold_mode gold t2_err_seg_minlen 4 no_validate_freq ZZ validate_epoch ZZ t2_err_match_addfirst ZZ t2_err_mcov_thresh 0.5" -z 6 -p 3
# x48
# nope
# maybe poisonous if too large t2_bad_lambda (drop to 15+) -> watch out!!: EOS issues -> 0.5 is still poison -> 0.1 still to 32+
#python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.00005 dicts ../../baselines/ze_ev/{src,trg}.v reload_model_name ../../baselines/ze_ev/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ patience 5 train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_maxlen 2 t2_bad_lambda 0.1 t2_err_seg_minlen 4" -z 6 -p 2
## again nga
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.00005 dicts ../../baselines/ze_ev/{src,trg}.v reload_model_name ../../baselines/ze_ev/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ patience 5 train_mode beam t2_beam_size 1 t2_sync_nga ZZ t2_beam_loss err t2_bad_maxlen 0 t2_err_gold_mode gold t2_nga_n 4 t2_nga_range 2 t2_err_match_addfirst ZZ" -z 6 -p 0
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.00005 dicts ../../baselines/ze_ev/{src,trg}.v reload_model_name ../../baselines/ze_ev/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ patience 5 train_mode beam t2_beam_size 1 t2_sync_nga ZZ t2_beam_loss err t2_bad_maxlen 0 t2_err_gold_mode based t2_nga_n 4 t2_nga_range 2 t2_err_match_addfirst ZZ" -z 6 -p 2
##
# no partials
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.00005 dicts ../../baselines/ze_ev/{src,trg}.v reload_model_name ../../baselines/ze_ev/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ patience 5 train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_maxlen 0 t2_err_gold_mode gold t2_err_seg_minlen 4 t2_err_match_addfirst ZZ t2_err_mcov_thresh 0.75 t2_err_pright_thresh 0.75" -z 6 -p 4
# some partials
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.00005 dicts ../../baselines/ze_ev/{src,trg}.v reload_model_name ../../baselines/ze_ev/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ patience 5 train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_maxlen 0 t2_err_gold_mode gold t2_err_seg_minlen 4 t2_err_match_addfirst ZZ t2_err_mcov_thresh 0.5 t2_err_pright_thresh 0.75" -z 6 -p 5
# all partials
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.00005 dicts ../../baselines/ze_ev/{src,trg}.v reload_model_name ../../baselines/ze_ev/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ patience 5 train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_maxlen 0 t2_err_gold_mode gold t2_err_seg_minlen 4 t2_err_match_addfirst ZZ" -z 6 -p 6
# some partials
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.00005 dicts ../../baselines/ze_ev/{src,trg}.v reload_model_name ../../baselines/ze_ev/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ patience 5 train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_maxlen 0 t2_err_gold_mode gold t2_err_seg_minlen 4 t2_err_match_addfirst ZZ t2_err_mcov_thresh 0.5" -z 6 -p 7
# x46
python3 ../../znmt/run/zprepare.py --zmt ../.. -d ../../zh_en_data/ -t znmt_zh --extras "gdrop_rec 0.2 idrop_embedding 0.0 drop_hidden 0.2 drop_embedding 0.2 lrate 0.00005 dicts ../../baselines/ze_ev/{src,trg}.v reload_model_name ../../baselines/ze_ev/zbest.model reload ZZ no_reload_training_progress ZZ no_rebuild_dicts ZZ valid_freq 5000 validate0 ZZ patience 3 train_mode beam t2_beam_size 1 t2_sync_med ZZ t2_beam_loss err t2_bad_maxlen 0 t2_err_gold_mode based t2_err_seg_minlen 4 t2_err_match_addfirst ZZ" -z 6 -p 3
